export type { DocumentOptions, OpenAPIInfo } from './document'
export { buildDocument } from './document'
export type { OpenAPIOptions } from './openapi'
export { openapi } from './openapi'
export type { ScalarOptions } from './scalar'
